### ISSUE TITLE
Use insert or ignore 

### ISSUE THREAD

**Issue by 91DarioDev** [Nhoya/YATAB#3]
Use insert or ignore instead of checking anytime if the data is already in the database if it is primary key to reduce the number of queries as i did here https://github.com/Nhoya/YATAB/commit/f2bea284be2a683c11e74add428e28008b94d92b

**Comment by Nhoya** [comment]
Thanks for the tip, i'm waiting for your pull request on `dev` branch, please next time do not open an issue, you can discuss on the PR thread
